config/routes.rb
StisJobs::Application.routes.draw do

  root to: "welcome_career/index", :to => "welcome_career#index"
  get "jobs/new", :to => "jobs#new", as: :jobs_new
  post "jobs/create"
  get "jobs/edit/:id", :to => "jobs#edit", as: :jobs_edit
  get "jobs/show/:id", :to => "jobs#show", as: :jobs_show
  get "jobs/index", :to => "jobs#index", as: :jobs_index
  delete "jobs/destroy/:id", :to => "jobs#destroy", as: :jobs_destroy
  post "jobs/update/:id", :to => "jobs#update", as: :jobs_update
  get "jobs/viewAllJobs", :to => "jobs#viewAllJobs", as: :jobs_viewAllJobs

  get "profile/new", :to => "profile#new", as: :profile_new
  get "profile/edit/:id", :to => "profile#edit", as: :profile_edit
  get "profile/show/:id", :to => "profile#show", as: :profile_show
  get "profile/index", :to => "profile#index", as: :profile_index
  post "profile/createProfile"
  post "profile/update/:id", :to => "profile#update", as: :profile_update
  delete "profile/destroy/:id", :to => "profile#destroy", as: :profile_destroy
  post "profile/create"
  get "profile/download", :to => "profile#download"
  get "profile/apply/:id", :to => "profile#apply", as: :profile_apply

  get "attachments/new", :to => "attachments#new"
  post "attachments/create"
  get "attachments/show/:id", :to => "attachments#show", as: :attachments_show
  get "attachments/index", :to => "attachments#index"

end

app/models/attachments.rb
class Attachments < ActiveRecord::Base

    has_many :profile_attachments, :dependent => :restrict
    has_one :profile, through: :profile_attachments

    #validates :data, presence: true

    def uploaded_file=(incoming_file)
        self.filename = incoming_file.original_filename
        self.content_type = incoming_file.content_type
        self.data = incoming_file.read
    end

    def filename=(new_filename)
        write_attribute("filename", sanitize_filename(new_filename))
    end

    private
    def sanitize_filename(filename)
        #get only the filename, not the whole path (from IE)
        just_filename = File.basename(filename)
        #replace all non-alphanumeric, underscore or periods with underscores
        just_filename.gsub(/[^\w\.\-]/, '_')
    end
end

app/models/jobs.rb
class Jobs < ActiveRecord::Base

	validates :designation, presence: true, length: {minimum: 2, maximum: 25}
	validates :responsibilites, presence: true, length: {minimum: 5, maximum: 250}
	validates :skills, presence: true, length: {minimum: 5, maximum: 250}
	validates :location, presence: true, length: {minimum: 2, maximum: 20}
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    has_many :profile_attachments, :dependent => :restrict
    has_one :attachments, through: :profile_attachments

    validates :email_id, presence: true, uniqueness: true
end

app/models/profile_attachments.rb
class ProfileAttachments < ActiveRecord::Base
	belongs_to :profile
	belongs_to :attachments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
	http_basic_authenticate_with name: "umer_rana@admin.com", password: "123456789", :only => [:index, :show]

	def new
		@attachment = Attachments.new
	end

	def index
		@attachment = Attachments.all
		@profile = Profile.all	
	end

	def show
		@attachment = Attachments.find(params[:id])
		send_data(@attachment.data, :filename => @attachment.filename, :type => @attachment.content_type, disposition: "inline")
	end

	def create
		if not params[:attachment].blank?
			if ( (params[:attachment].content_type == "application/vnd.openxmlformats-officedocument.wordprocessingml.document") || ((params[:attachment].content_type == "application/pdf")))
		
				@attachment = Attachments.new
				
				@attachment.uploaded_file = params[:attachment]

				if @attachment.save
					profileId = Profile.last
					relProfileId = ProfileAttachments.where(:profile_id => profileId)
					attachmentId = @attachment.id
					relProfileId.first.attachments_id = attachmentId
					relProfileId.first.save
					flash[:alert] = "Thank You for applying"
					redirect_to root_path
				else
					flash[:alert] = "Problem in applying"
					redirect_to :back			
				end
			else
				flash[:alert] = "Allow pdf and docx file only"
				redirect_to :back	
			end

		else
			flash[:alert] = "File Not Present"
			redirect_to :back
		end

	end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	
  http_basic_authenticate_with name: "umer_rana@admin.com", password: "123456789", :only => [:index, :editJobs, :destroy]

  def new
  	@jobs = Jobs.new
  end

  def index
  	@jobs = Jobs.all
  end

  def show
  	@jobs = Jobs.find(params[:id])
  end

  def edit
  	@editJobs = Jobs.find(params[:id])
  end

  def create
  	@jobs = Jobs.new(jobs_params)
  	if @jobs.save
      flash[:notice] = "Job Successfully Post"
  		redirect_to jobs_index_path
  	else
  		render jobs_new_path
  	end
  end

  def update
  	@editJobs = Jobs.find(params[:id])
  	if @editJobs.update(params[:jobs].permit(:designation, :experience, :gender, :responsibilites, :skills, :qualification, :location,))
  		redirect_to jobs_index_path
  	else
  		render jobs_edit_path
  	end
  end

  def destroy
  	@jobs = Jobs.find(params[:id])
  	@jobs.delete

  	redirect_to jobs_index_path
  end

  def viewAllJobs
    @jobs = Jobs.all
  end

  private
  def jobs_params
  	params.require(:jobs).permit(:designation , :experience, :gender, :responsibilites, :skills, :qualification, :location,)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	http_basic_authenticate_with name: "umer_rana@admin.com", password: "123456789", :only => [:index, :edit, :show, :destroy]

	def new
		#@jobs= Jobs.find(params[:id])
		@profile = Profile.new
	end

	def show
		@profile = Profile.find(params[:id])
	end

	def edit
		@editProfile = Profile.find(params[:id])
	end

	def index

		@profile = Profile.all
		@rel = ProfileAttachments.all
	end

	def update
		@editProfile = Profile.find(params[:id])
	  	if @editProfile.update(params[:profile].permit(:fullName, :email, :mobileNo, :phoneNo, :experience, :qualification, :certification, :jobDesignation))
	  		redirect_to profile_index_path
	  	else
	  		render profile_edit_path
	  	end
	end

	def create
		@profile = Profile.new(params_profile)
		#if !(@profile.errors.any?)
		if @profile.save
			profile = @profile.id
			@rel = ProfileAttachments.new(:profile_id => profile)
			@rel.save
			flash[:notice] = "You profile data successfully send. Kindly upload your cv"
			redirect_to attachments_new_path
		else
			flash[:alert] = "Email not be empty OR You will already applied through this email  Name Should not e blank"
			#flash[:notice] = "You have successfully logged out."
			redirect_to :back
		end
		# else
		# 	flash[:alert] = "Email not be empty"
		# 	redirect_to root_path	
		#end
		
	end

	def destroy
		@profile = Profile.find(params[:id])
		@profile.delete

		redirect_to profile_index_path
	end

	def apply
		@jobs = Jobs.find(params[:id])
		@profile = Profile.new
	end
	# def download
	# 	@profileID = params[:id]
	# 	rel = ProfileAttachments.where(:profile_id => @profileID)
	# 	result = rel.first.attachments_id
	# 	if !(result == nil)
	# 		redirect_to attachments_show_path(result)
	# 	end
	# end

	private
	def params_profile
		params.require(:profile).permit(:fullName, :email_id, :mobileNo, :phoneNo, :experience, :qualification, :certification, :jobDesignation)
	end
end

app/controllers/welcome_career_controller.rb
class WelcomeCareerController < ApplicationController
  def index
  	flash[:notice] = "Welcome to Stis Career Site"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/welcome_career_helper.rb
module WelcomeCareerHelper
end

app/views/attachments/index.html.haml
-if @profile.blank?
	%h3= "No Profile to show"
	%div
		=link_to 'Apply For Job', profile_new_path, :class => "btn btn-primary"
	%br
-else
	%h3.text-center
		= "Showing the list of all appllied jobs in SciTech IT Services"
	%div.text-center
		=link_to 'Apply For Job', profile_new_path, :class => "btn btn-primary"
		|
		=link_to 'Post Jobs', jobs_new_path, :class => "btn btn-primary"
	%br
	%div
		%table.table.table-hover.table-condensed.text-center
			%tr
				%th.col-lg-1.text-center
					Full Name
				%th.col-lg-1.text-center
					Email
				%th.col-lg-1.text-center
					Mobile No
				%th.col-lg-1.text-center
					Phone No
				%th.col-lg-1.text-center
					Experinece
				%th.col-lg-1.text-center
					Qualfication
				%th.col-lg-1.text-center
					Certification
				%th.col-lg-2.text-center 
					Options
			-@profile.each do |j|
				%tr
					%td= j.fullName
					%td= j.email
					%td= j.mobileNo
					%td= j.phoneNo
					%td= j.experience
					%td= j.qualification
					%td= j.certification
					%td
						= link_to profile_show_path(j.id) do
							= content_tag :button, :class => "btn btn-primary" do
								= content_tag :span, class: "glyphicon glyphicon-list" do
									=""
						= link_to profile_edit_path(j.id) do
							= content_tag :button, :class => "btn btn-warning" do
								= content_tag :span, class: "glyphicon glyphicon-pencil" do
									=""
						|
						= link_to profile_destroy_path(j.id), method: :delete, data: { :confirm => 'Are you sure?' } do
							= content_tag :button, :class => "btn btn-danger" do
								= content_tag :span, class: "glyphicon glyphicon-remove" do
									=""

app/views/attachments/new.html.haml
%h5.text-center
	Upload Your CV or Resuma here
%div.container.well
	= form_tag 'create', :multipart => true, class: "form-horizontal" do 
		%div.text-center.container
			%div.input-group
				= file_field_tag 'attachment', :id => "exampleInputFile" 
				%br
				= submit_tag "Upload", :class => "btn btn-primary" 

app/views/attachments/show.html.haml
%h5.text-center
	= "Listing Users Cv's => #{@attachment.filename}"
%p
	= image_tag url_for(:action => 'show', :id => @attachment.id)

app/views/jobs/edit.html.haml
%h5
	= "Editing #{@editJobs.designation} Job" 
=form_for :jobs, url:{action: "update"}, html:{class: "form-horizontal"} do |f|
	%div.form-group
		=f.label :designation, 'Designation' , {:class => 'col-lg-2 control-label'}
		%span.error_message
			- if not (@editJobs.errors[:designation].blank?)
				=@editJobs.errors[:designation].second
		%div.col-lg-3
			=f.text_field :designation, {:class => 'form-control', :value => @editJobs.designation}
	%div.form-group
		=f.label :experience, 'Experience', {:class => 'col-lg-2 control-label'}
		%div.col-lg-3
			=f.select(:experience, ['0-2 Years', '2-3 Years', '5-8 Years', '8 Years Plus'], {}, {:class => 'form-control', :placeholder => ""})
	%div.form-group
		=f.label :gender, 'Gender', {:class => 'col-lg-2 control-label'}
		%div.col-lg-3
			=f.select(:gender, ['Male', 'Female', 'N/A'], {}, {:class => 'form-control', :placeholder => ""})
	%div.form-group
		=f.label :responsibilites, 'Responsibilities' , {:class => 'col-lg-2 control-label'}
		%span.error_message
			- if not (@editJobs.errors[:responsibilites].blank?)
				=@editJobs.errors[:responsibilites].to_s
		%div.col-lg-3	
			=f.text_area :responsibilites, {:class => 'form-control' , :value => @editJobs.responsibilites}
	%div.form-group
		=f.label :skills, 'Skills', {:class => 'col-lg-2 control-label'}
		%span.error_message
			- if not (@editJobs.errors[:skills].blank?)
				=@editJobs.errors[:skills].to_s
		%div.col-lg-3
			=f.text_field :skills, {:class => 'form-control' , :value => @editJobs.skills}
	%div.form-group
		=f.label :qualification, 'Qualification', {:class => 'col-lg-2 control-label'}
		%div.col-lg-3
			=f.select(:qualification, ['Graduate 2-3 Years', 'Graduate 4-5 Years', 'Post-Graduate 5+', 'N/A'], {}, {:class => 'form-control', :placeholder => ""})
	%div.form-group
		=f.label :location, 'Location', {:class => 'col-lg-2 control-label'}
		%div.col-lg-3
			=f.text_field :location, {:class => 'form-control', :value => @editJobs.location}
	%div.form-group
		%div.col-lg-offset-2.col-lg-10
			=f.submit :class => 'btn btn-primary'
			= link_to "See All Jobs", jobs_index_path, :class => "btn btn-primary"

app/views/jobs/index.html.haml
-if @jobs.blank?
	%h5= "No jobs to show"
	%div
		=link_to 'Post new Job', jobs_new_path, :class => "btn btn-primary"
	%br
-else
	%h5.text-center
		= "Showing the list of all jobs in SciTech IT Services"
	%div.text-center
		=link_to 'View All Job', jobs_viewAllJobs_path, :class => "btn btn-primary"
		|
		=link_to 'Post Jobs', jobs_new_path, :class => "btn btn-primary"
	%br
	%div
		%table.table.table-hover.table-condensed.text-center
			%tr
				%th.col-lg-1.text-center
					Designation
				%th.col-lg-1.text-center
					Experience
				%th.col-lg-1.text-center
					Gender
				%th.col-lg-3.text-center
					Responsibilities
				%th.col-lg-2.text-center
					Skills
				%th.col-lg-1.text-center
					Qualfication
				%th.col-lg-1.text-center
					Location
				%th.col-lg-4.text-center 
					Options
			-@jobs.each do |j|
				%tr
					%td
						= j.designation
					%td
						= j.experience
					%td
						= j.gender
					%td
						= j.responsibilites
					%td
						= j.skills
					%td
						= j.qualification
					%td
						= j.location
					%td
						= link_to jobs_show_path(j.id) do
							= content_tag :button, :class => "btn btn-primary" do
								= content_tag :span, class: "glyphicon glyphicon-list" do
									=""
						|
						= link_to jobs_edit_path(j.id) do
							= content_tag :button, :class => "btn btn-warning" do
								= content_tag :span, class: "glyphicon glyphicon-pencil" do
									=""
						|
						= link_to jobs_destroy_path(j.id), method: :delete, data: { :confirm => 'Are you sure?' } do
							= content_tag :button, :class => "btn btn-danger" do
								= content_tag :span, class: "glyphicon glyphicon-remove" do
									=""

app/views/jobs/new.html.haml
%br
%br
%h5.text-center Post New Job
%hr
=form_for :jobs, url:{action: "create"}, html:{class: "form-horizontal"} do |f|
	%div.form-group
		=f.label :designation, 'Designation' , {:class => 'col-lg-2 control-label'}
		%span.error_message
			- if not (@jobs.errors[:designation].blank?)
				=@jobs.errors[:designation].second
		%div.col-lg-3
			=f.text_field :designation, {:class => 'form-control', :placeholder => "Developer"}
	%div.form-group
		=f.label :experience, 'Experience', {:class => 'col-lg-2 control-label'}
		%div.col-lg-3
			=f.select(:experience, ['0-2 Years', '2-3 Years', '5-8 Years', '8 Years Plus'], {}, {:class => 'form-control', :placeholder => ""})
	%div.form-group
		=f.label :gender, 'Gender', {:class => 'col-lg-2 control-label'}
		%div.col-lg-3
			=f.select(:gender, ['Male', 'Female', 'N/A'], {}, {:class => 'form-control', :placeholder => ""})
	%div.form-group
		=f.label :responsibilites, 'Responsibilities' , {:class => 'col-lg-2 control-label'}
		%span.error_message
			- if not (@jobs.errors[:responsibilites].blank?)
				=@jobs.errors[:responsibilites].to_s
		%div.col-lg-3	
			=f.text_area :responsibilites, {:class => 'form-control' , :placeholder => "Write Responsibilities"}
	%div.form-group
		=f.label :skills, 'Skills', {:class => 'col-lg-2 control-label'}
		%span.error_message
			- if not (@jobs.errors[:skills].blank?)
				=@jobs.errors[:skills].to_s
		%div.col-lg-3
			=f.text_area :skills, {:class => 'form-control' , :placeholder => "Skills"}
	%div.form-group
		=f.label :qualification, 'Qualification', {:class => 'col-lg-2 control-label'}
		%div.col-lg-3
			=f.select(:qualification, ['Graduate 2-3 Years', 'Graduate 4-5 Years', 'Post-Graduate 5+', 'N/A'], {}, {:class => 'form-control', :placeholder => ""})
	%div.form-group
		=f.label :location, 'Location', {:class => 'col-lg-2 control-label'}
		%span.error_message
			- if not (@jobs.errors[:location].blank?)
				=@jobs.errors[:location].to_s
		%div.col-lg-3
			=f.text_field :location, {:class => 'form-control', :placeholder => "Lahore, Karachi, Islamabad"}
	%div.form-group
		%div.col-lg-offset-2.col-lg-10
			=f.submit :class => 'btn btn-primary'
			= link_to jobs_index_path do
				= content_tag :button, class: "btn btn-default" do
					="Cancel"

app/views/jobs/show.html.haml
-if @jobs.blank?
	%h5= "No jobs to show"
	%div
		=link_to 'Post new Job', jobs_new_path, :class => "btn btn-primary"
	%br
-else
	%h5.text-center
		= "Showing the list of all jobs in SciTech IT Services"
	%div.text-center
		=link_to "Apply Now", profile_apply_path(@jobs.id), :class => "btn btn-success"
		|
		=link_to 'View All Job', jobs_viewAllJobs_path, :class => "btn btn-primary"
	%br
	%hr
	%div.container.text-center.pull-right
		%div.list-group.col-lg-3
			%a.list-group-item
				%h4.list-group-item-heading
					Designation
				%p.list-group-item-text
					-if(@jobs.designation.blank?)
						="--"
					-else
						=@jobs.designation.capitalize
	%div.container.text-center.pull-right
		%div.list-group.col-lg-3
			%a.list-group-item
				%h4.list-group-item-heading
					Gender
				%p.list-group-item-text
					-if(@jobs.gender.blank?)
						="--"
					-else
						=@jobs.gender.capitalize
	%div.container.text-center.pull-right	
		%div.list-group.col-lg-3
			%a.list-group-item
				%h4.list-group-item-heading
					Experience
				%p.list-group-item-text
					=@jobs.experience	
	%div.container.text-center.pull-right
		%div.list-group.col-lg-3
			%a.list-group-item
				%h4.list-group-item-heading
					Qualification
				%p.list-group-item-text
					-if(@jobs.qualification.blank?)
						="--"
					-else
						=@jobs.qualification.capitalize
	%div.container.text-center.pull-right		
		%div.list-group.col-lg-3
			%a.list-group-item
				%h4.list-group-item-heading
					Locations 
				%p.list-group-item-text
					-if(@jobs.location.blank?)
						="--"
					-else
						=@jobs.location.capitalize
	%div.container.text-center.pull-right
		%div.list-group.col-lg-5
			%a.list-group-item
				%h4.list-group-item-heading
					Responsibilities
				%p.list-group-item-text
					=@jobs.responsibilites
	%div.container.text-center.pull-right
		%div.list-group.col-lg-5
			%a.list-group-item
				%h4.list-group-item-heading
					Skills
				%p.list-group-item-text
					-if(@jobs.skills.blank?)
						="--"
					-else
						=@jobs.skills

app/views/jobs/viewAllJobs.html.haml
-if @jobs.blank?
	%h5.text-center
		= "No jobs to show"
	%div.text-center
		=link_to 'Post new Job', jobs_new_path, :class => "btn btn-primary"
	%br
-else
	%h5.text-center
		= "Showing the list of all jobs in SciTech IT Services"
	%br
	%br
	%div
		%table.table.table-hover.table-condensed.text-center
			%tr
				%th.col-lg-1.text-center
					Designation
				%th.col-lg-1.text-center
					Experience
				%th.col-lg-1.text-center
					Gender
				%th.col-lg-3.text-center
					Responsibilities
				%th.col-lg-2.text-center
					Skills
				%th.col-lg-1.text-center
					Qualfication
				%th.col-lg-1.text-center
					Location
				%th.col-lg-4.text-center 
					Apply
			-@jobs.each do |j|
				%tr
					%td
						= j.designation
					%td
						= j.experience
					%td
						= j.gender
					%td
						= j.responsibilites
					%td
						= j.skills
					%td
						= j.qualification
					%td
						= j.location
					%td
						= link_to profile_apply_path(j.id) do
							= content_tag :button, :class => "btn btn-success" do
								="Apply Now"
						|
						= link_to jobs_show_path(j.id) do
							= content_tag :button, :class => "btn btn-info" do
								="Show Details"

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
	%head
		%title SciTech
		= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
		= javascript_include_tag "application", "data-turbolinks-track" => true
		= csrf_meta_tags
	%body#body-css	
		%div#container.text-center
			%div#logo
				= image_tag "logo1.png"
		%h4.text-center Welcome to SciTech IT Services Carrier Portfolio
		-if(flash[:notice].blank? == false)
			%div.alert.alert-dismissable.alert-warning.text-center
				%button.close{:href => "#", :data => {:dismiss => "alert"}, :aria=> {:hidden => "true"}}
					&times;
				%span
					=flash[:notice]
		-if(flash[:alert].blank? == false)
			%div.alert.alert-dismissable.alert-danger.text-center
				%button.close{:href => "#", :data => {:dismiss => "alert"}, :aria=> {:hidden => "true"}}
					&times;
				%span
					=flash[:alert]
		= yield

app/views/welcome_career/index.html.haml
%p.text-center
	=link_to "View All Jobs", jobs_viewAllJobs_path, :method => :get, :class => "btn btn-primary"